name: Run Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting (if you have ESLint)
      run: npm run lint
      continue-on-error: false
    
    - name: Run type checking (if you have TypeScript)
      run: npm run type-check
      continue-on-error: false
    
    - name: Run Vitest tests
      run: npm run test
      env:
        # Set any environment variables your tests need
        NODE_ENV: test
        # If using the conditional approach for edge cases:
        # RUN_EDGE_CASES: true
    
    - name: Run test coverage (optional)
      run: npm run test:coverage
      continue-on-error: true
    
    - name: Upload coverage reports (optional)
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella